# Generated by Django 5.0.3 on 2024-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Electronics', max_length=100)),
                ('image', models.ImageField(default='category/default_category_image/img.png', upload_to='category/category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
