# Generated by Django 4.2.10 on 2026-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='vendor_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='vendor_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
