# Generated by Django 5.0.3 on 2024-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_images_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_product_image/img.png', max_length=300, upload_to='products/product_image/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='products/product_images/'),
        ),
    ]
