# Generated by Django 5.0.3 on 2024-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Electronics', max_length=100, unique=True),
        ),
    ]
