# Generated by Django 5.0.3 on 2024-10-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_status_category_num_of_products_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='products.product'),
        ),
    ]
