# Generated by Django 5.0.3 on 2026-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/banner_images/'),
        ),
    ]
