# Generated by Django 5.0.3 on 2024-11-02 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Electro Shop', max_length=100)),
                ('logo', models.ImageField(default='vendors/default_vendor_image/img.png', upload_to='vendors/logo/')),
                ('banner_image', models.ImageField(default='vendors/default_banner_image/default_banner_image.webp', upload_to='vendors/banner_images/')),
                ('description', models.TextField(blank=True, default='Amazing vendor', null=True)),
                ('address', models.CharField(default='123 Main Street', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='+251946472687', max_length=15)),
                ('website', models.URLField(blank=True)),
                ('chat_response_time', models.PositiveIntegerField(default=100)),
                ('shipping_on_time', models.PositiveIntegerField(default=100)),
                ('authentic_rating', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('days_return', models.PositiveIntegerField(default=30)),
                ('warranty_period', models.PositiveIntegerField(default=12)),
                ('vendor_share_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default='bank_transfer', max_length=50)),
                ('subscription_plan', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
