# Generated by Django 5.0.3 on 2024-10-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(default='vendors/default_banner_image/default_banner_image.webp', upload_to='vendors/banner_images/'),
        ),
    ]
