# Generated by Django 5.0.3 on 2024-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='123 Main Street', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_res_time',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_on_time',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Electro Shop', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
