# Generated by Django 5.0.3 on 2024-11-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='subscription_fee',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_share_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vendorpayment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default='bank_transfer', max_length=50),
        ),
    ]
