# Generated by Django 5.0.3 on 2026-08-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='vendors.vendor'),
        ),
    ]
