# Generated by Django 5.0.3 on 2024-06-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='usrname',
        ),
    ]
