# Generated by Django 5.0.3 on 2024-06-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_name_user_usrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usrname',
            new_name='username',
        ),
    ]
