import uuid
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from rest_framework.decorators import api_view, permission_classes
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status

from orders.models import Order
from .models import Payment
from .serializers import PaymentSerializer
from chapa import Chapa
from .check_payment import verify_payment

# Initialize Chapa with your secret key
chapa = Chapa(settings.CHAPA_SECRET_KEY)
class CreatePaymentView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        amount = request.data.get('total_amount')
        email = request.data.get('email')
        first_name = request.data.get('first_name')
        last_name = request.data.get('last_name')
        phone_number = request.data.get('phone_number')

        if not all([amount, email,first_name]):
            print('not get email,amount,firstname')
            return Response({"error": "Amount, email, and first name are required."}, status=status.HTTP_400_BAD_REQUEST)
        frontend_url=settings.FRONTEND_URL
        payment_ref = f"multi-txn-{uuid.uuid4().hex[:8]}"
        payment_data = {
            "amount": amount,
            "currency": "ETB",
            "email": email,
            "first_name": first_name,
            "last_name": last_name,
            "phone_number": phone_number,
            "tx_ref": payment_ref,  
            "return_url": f"{frontend_url}/payment/confirm?txt_ref={payment_ref}"
        }

        try:
            print('try block')
            response = chapa.initialize(**payment_data)
            if response['status'] == 'success':
                checkout_url = response['data']['checkout_url']
                
                print('success full initiation')
                return Response({"data": {"checkout_url": checkout_url, "payment_ref": payment_ref}}, status=status.HTTP_200_OK)

            return Response(response, status=status.HTTP_400_BAD_REQUEST)

        except Exception as e:
            return Response({"error": "Payment initialization failed."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
@csrf_exempt
@api_view(['GET'])
def chapa_callback(request):
    pass


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def check_payment_status(request, payment_reference):
    """
    `payment_reference` is the single Chapa `tx_ref` that was actually charged
    (a lump sum covering every order in this checkout session, generated by
    CreatePaymentView). `transaction_ids` is the list of this app's own
    per-order Payment.transaction_id values — these were never sent to Chapa,
    they're only used here to look up which local Order/Payment rows this
    lump payment should be applied to. So Chapa is verified once, against
    payment_reference, and on success every listed Payment is marked paid.
    """
    transaction_ids = request.GET.get('transaction_ids')
    if not transaction_ids:
        return Response({"error": "transaction_ids are required."}, status=status.HTTP_400_BAD_REQUEST)

    transaction_ids = transaction_ids.split(",")

    try:
        verification = verify_payment(payment_reference)
    except Exception as e:
        return Response({"error": f"Payment verification failed: {str(e)}"}, status=status.HTTP_502_BAD_GATEWAY)

    payment_succeeded = bool(verification and verification.get('status') == 'success')

    total_amount = 0
    user = None
    payment_responses = []

    for tx_ref in transaction_ids:
        payment = Payment.objects.filter(transaction_id=tx_ref).first()

        if not payment:
            payment_responses.append({"transaction_id": tx_ref, "status": "error", "message": "Payment not found"})
            continue

        if not payment.order or payment.order.user_id != request.user.id:
            payment_responses.append({"transaction_id": tx_ref, "status": "error", "message": "Not authorized for this payment"})
            continue

        if payment_succeeded:
            payment.payment_status = 'completed'
            payment.save()

            order = payment.order
            order.status = 'completed'
            order.save()

            vendor = order.vendor
            if vendor:
                vendor.balance += payment.amount
                vendor.save()

            total_amount += payment.amount
            if not user:
                user = order.user

            payment_responses.append({"transaction_id": tx_ref, "status": "completed", "payment": PaymentSerializer(payment).data})
        else:
            payment.payment_status = 'failed'
            payment.save()
            payment_responses.append({"transaction_id": tx_ref, "status": "failed", "message": "Payment verification failed"})

    if user and total_amount:
        user.balance -= total_amount
        user.save()

    return Response({"payments": payment_responses}, status=status.HTTP_200_OK)