import uuid
import logging
from decimal import Decimal, InvalidOperation
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from rest_framework import generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import PermissionDenied
from rest_framework import status

from orders.models import Order
from users.models import CustomUser
from vendors.models import Vendor
from .models import Payment, PaymentSession, WithdrawalRequest, PAYMENT_STATUS
from .serializers import PaymentSerializer, VendorPaymentSerializer, WithdrawalRequestSerializer
from .services import finalize_payment_session
from chapa import Chapa
from .check_payment import verify_payment
from notifications.utils import notify

logger = logging.getLogger(__name__)

# Initialize Chapa with your secret key
chapa = Chapa(settings.CHAPA_SECRET_KEY)
class CreatePaymentView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        amount = request.data.get('total_amount')
        email = request.data.get('email')
        first_name = request.data.get('first_name')
        last_name = request.data.get('last_name')
        phone_number = request.data.get('phone_number')
        transaction_ids = request.data.get('transaction_ids') or []

        if not all([amount, email,first_name]):
            print('not get email,amount,firstname')
            return Response({"error": "Amount, email, and first name are required."}, status=status.HTTP_400_BAD_REQUEST)
        frontend_url=settings.FRONTEND_URL
        payment_ref = f"multi-txn-{uuid.uuid4().hex[:8]}"

        # Link this one Chapa charge back to the local Payment rows it
        # covers (checkout splits the cart into one Order+Payment per
        # vendor) so the webhook — which has no access to the browser —
        # can later resolve which orders to mark paid.
        payments = Payment.objects.filter(
            transaction_id__in=transaction_ids, order__user=request.user
        )
        if payments.exists():
            session = PaymentSession.objects.create(tx_ref=payment_ref, user=request.user, amount=amount)
            session.payments.set(payments)

        payment_data = {
            "amount": amount,
            "currency": "ETB",
            "email": email,
            "first_name": first_name,
            "last_name": last_name,
            "phone_number": phone_number,
            "tx_ref": payment_ref,
            "return_url": f"{frontend_url}/payment/confirm?txt_ref={payment_ref}",
            "callback_url": request.build_absolute_uri(reverse('chapa-webhook', args=[payment_ref])),
        }

        try:
            print('try block')
            response = chapa.initialize(**payment_data)
            if response['status'] == 'success':
                checkout_url = response['data']['checkout_url']

                print('success full initiation')
                return Response({"data": {"checkout_url": checkout_url, "payment_ref": payment_ref}}, status=status.HTTP_200_OK)

            return Response(response, status=status.HTTP_400_BAD_REQUEST)

        except Exception as e:
            return Response({"error": "Payment initialization failed."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@csrf_exempt
@api_view(['POST'])
def chapa_callback(request, tx_ref):
    """Server-to-server webhook Chapa calls when a transaction's status
    changes. Never trusts the POST body's claimed status — it's only a
    trigger to re-verify with Chapa directly using our own secret key,
    the same check the polling endpoint performs. Always acknowledges
    with 200 so Chapa doesn't retry; failures are logged, not surfaced."""
    session = PaymentSession.objects.filter(tx_ref=tx_ref).first()
    if not session:
        logger.warning('Chapa webhook for unknown tx_ref %s', tx_ref)
        return Response(status=status.HTTP_200_OK)

    try:
        verification = verify_payment(tx_ref)
        finalize_payment_session(session, verification or {})
    except Exception:
        logger.exception('Chapa webhook processing failed for tx_ref %s', tx_ref)

    return Response(status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def check_payment_status(request, payment_reference):
    """
    `payment_reference` is the single Chapa `tx_ref` that was actually charged
    (a lump sum covering every order in this checkout session, generated by
    CreatePaymentView). `transaction_ids` is the list of this app's own
    per-order Payment.transaction_id values — these were never sent to Chapa,
    they're only used here to look up which local Order/Payment rows this
    lump payment should be applied to. So Chapa is verified once, against
    payment_reference, and on success every listed Payment is marked paid.
    """
    transaction_ids_param = request.GET.get('transaction_ids')
    if not transaction_ids_param:
        return Response({"error": "transaction_ids are required."}, status=status.HTTP_400_BAD_REQUEST)

    transaction_ids = transaction_ids_param.split(",")

    try:
        verification = verify_payment(payment_reference)
    except Exception as e:
        return Response({"error": f"Payment verification failed: {str(e)}"}, status=status.HTTP_502_BAD_GATEWAY)

    session = PaymentSession.objects.filter(tx_ref=payment_reference, user=request.user).first()
    if not session:
        # Legacy fallback: a payment initiated before PaymentSession
        # existed has no session yet — create one now from the
        # transaction_ids the client remembers, so this (and any later
        # webhook hit for the same tx_ref) can use the same idempotent
        # path going forward.
        legacy_payments = Payment.objects.filter(
            transaction_id__in=transaction_ids, order__user=request.user
        )
        if legacy_payments.exists():
            session = PaymentSession.objects.create(
                tx_ref=payment_reference,
                user=request.user,
                amount=sum(p.amount for p in legacy_payments),
            )
            session.payments.set(legacy_payments)

    payment_responses = []
    if session:
        # Idempotent — a no-op if a webhook already finalized this session.
        finalize_payment_session(session, verification or {})

        found_ids = set()
        for payment in session.payments.filter(transaction_id__in=transaction_ids):
            found_ids.add(payment.transaction_id)
            if payment.payment_status == 'completed':
                payment_responses.append({"transaction_id": payment.transaction_id, "status": "completed", "payment": PaymentSerializer(payment).data})
            elif payment.payment_status == 'failed':
                payment_responses.append({"transaction_id": payment.transaction_id, "status": "failed", "message": "Payment verification failed"})
            else:
                payment_responses.append({"transaction_id": payment.transaction_id, "status": "pending"})
        for tx_ref in transaction_ids:
            if tx_ref not in found_ids:
                payment_responses.append({"transaction_id": tx_ref, "status": "error", "message": "Payment not found"})
    else:
        for tx_ref in transaction_ids:
            payment_responses.append({"transaction_id": tx_ref, "status": "error", "message": "Not authorized for this payment"})

    return Response({"payments": payment_responses}, status=status.HTTP_200_OK)


class VendorPaymentsView(generics.ListAPIView):
    """Payment history for the authenticated vendor's own orders."""
    serializer_class = VendorPaymentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.role == 'admin':
            return Payment.objects.select_related('order', 'order__user').all()
        vendor = Vendor.objects.filter(user=user).first()
        if not vendor:
            return Payment.objects.none()
        return Payment.objects.select_related('order', 'order__user').filter(order__vendor=vendor)


class PaymentDetailView(generics.RetrieveAPIView):
    """A single payment's detail — an admin can view any payment, a vendor
    only one on their own order. PATCH is a manual admin-only status
    override for reconciliation (e.g. marking a payment refunded) — it
    updates local bookkeeping only and never calls out to the payment
    gateway."""
    serializer_class = VendorPaymentSerializer
    queryset = Payment.objects.select_related('order', 'order__user', 'order__vendor')
    permission_classes = [IsAuthenticated]

    def get_object(self):
        obj = super().get_object()
        user = self.request.user
        if user.role == 'admin':
            return obj
        vendor = Vendor.objects.filter(user=user).first()
        if obj.order and vendor and obj.order.vendor_id == vendor.id:
            return obj
        raise PermissionDenied("You can't view another vendor's payment.")

    def patch(self, request, *args, **kwargs):
        if request.user.role != 'admin':
            raise PermissionDenied('Only an admin can change a payment status.')

        payment = self.get_object()
        new_status = request.data.get('payment_status')
        valid_statuses = dict(PAYMENT_STATUS)
        if new_status not in valid_statuses:
            return Response({'detail': 'Invalid payment status.'}, status=status.HTTP_400_BAD_REQUEST)

        old_status = payment.payment_status
        payment.payment_status = new_status
        payment.save(update_fields=['payment_status', 'updated_at'])

        if new_status == 'refunded' and old_status != 'refunded' and payment.order:
            order = payment.order
            order.status = 'refunded'
            order.save(update_fields=['status', 'updated_at'])
            vendor = order.vendor
            if vendor:
                vendor.balance = max(vendor.balance - payment.amount, 0)
                vendor.save(update_fields=['balance'])

        return Response(self.get_serializer(payment).data)


class WithdrawalRequestListCreateView(generics.ListCreateAPIView):
    """A vendor's manual payout queue: they request a withdrawal, an
    admin reviews it and marks it paid/rejected outside the app (no
    live money-movement API involved)."""
    serializer_class = WithdrawalRequestSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.role == 'admin':
            qs = WithdrawalRequest.objects.select_related('vendor').all()
            vendor_id = self.request.query_params.get('vendor')
            return qs.filter(vendor_id=vendor_id) if vendor_id else qs
        vendor = Vendor.objects.filter(user=user).first()
        if not vendor:
            return WithdrawalRequest.objects.none()
        return WithdrawalRequest.objects.filter(vendor=vendor)

    def create(self, request, *args, **kwargs):
        vendor = Vendor.objects.filter(user=request.user).first()
        if not vendor:
            raise PermissionDenied('Only a vendor can request a withdrawal.')

        try:
            amount = Decimal(str(request.data.get('amount')))
        except (InvalidOperation, TypeError):
            return Response({'error': 'A valid amount is required.'}, status=status.HTTP_400_BAD_REQUEST)
        if amount <= 0:
            return Response({'error': 'Amount must be greater than zero.'}, status=status.HTTP_400_BAD_REQUEST)

        account_details = request.data.get('account_details')
        if not account_details:
            return Response({'error': 'Account details are required.'}, status=status.HTTP_400_BAD_REQUEST)

        with transaction.atomic():
            locked_vendor = Vendor.objects.select_for_update().get(id=vendor.id)
            if amount > locked_vendor.balance:
                return Response({'error': 'Amount exceeds your available balance.'}, status=status.HTTP_400_BAD_REQUEST)

            locked_vendor.balance -= amount
            locked_vendor.save(update_fields=['balance'])

            withdrawal = WithdrawalRequest.objects.create(
                vendor=locked_vendor,
                amount=amount,
                payout_method=request.data.get('payout_method', 'bank_transfer'),
                account_details=account_details,
            )

        try:
            for admin in CustomUser.objects.filter(role='admin'):
                notify(
                    recipient=admin,
                    notification_type='system',
                    title=f'{vendor.title} requested a withdrawal',
                    message=f'{amount} ETB via {withdrawal.get_payout_method_display()}.',
                    link='/admin-dashboard/payouts',
                )
        except Exception:
            pass

        return Response(self.get_serializer(withdrawal).data, status=status.HTTP_201_CREATED)


class WithdrawalRequestDetailView(generics.RetrieveUpdateAPIView):
    """Admin-only review of a single withdrawal request. Rejecting
    refunds the reserved amount back to the vendor's balance; marking
    paid leaves it deducted (the payout happened outside the app)."""
    serializer_class = WithdrawalRequestSerializer
    queryset = WithdrawalRequest.objects.select_related('vendor')
    permission_classes = [IsAuthenticated]

    def get_object(self):
        obj = super().get_object()
        user = self.request.user
        if user.role == 'admin':
            return obj
        vendor = Vendor.objects.filter(user=user).first()
        if vendor and obj.vendor_id == vendor.id:
            return obj
        raise PermissionDenied("You can't view another vendor's withdrawal request.")

    def patch(self, request, *args, **kwargs):
        if request.user.role != 'admin':
            raise PermissionDenied('Only an admin can review a withdrawal request.')

        withdrawal = self.get_object()
        if withdrawal.status != 'pending':
            return Response({'error': 'This request was already reviewed.'}, status=status.HTTP_400_BAD_REQUEST)

        new_status = request.data.get('status')
        if new_status not in ('paid', 'rejected'):
            return Response({'error': 'status must be "paid" or "rejected".'}, status=status.HTTP_400_BAD_REQUEST)

        withdrawal.status = new_status
        withdrawal.admin_note = request.data.get('admin_note', '')
        withdrawal.reviewed_by = request.user
        withdrawal.reviewed_at = timezone.now()
        withdrawal.save(update_fields=['status', 'admin_note', 'reviewed_by', 'reviewed_at'])

        if new_status == 'rejected':
            vendor = withdrawal.vendor
            vendor.balance += withdrawal.amount
            vendor.save(update_fields=['balance'])

        try:
            notify(
                recipient=withdrawal.vendor.user,
                notification_type='system',
                title=f'Withdrawal {new_status}',
                message=f'Your request for {withdrawal.amount} ETB was {new_status}.' + (
                    f' Note: {withdrawal.admin_note}' if withdrawal.admin_note else ''
                ),
                link='/vendor-dashboard/payments',
            )
        except Exception:
            pass

        return Response(self.get_serializer(withdrawal).data)