# Generated by Django 5.0.3 on 2024-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'Paypal')], default='chapa', max_length=50),
        ),
    ]
