# Generated by Django 5.0.3 on 2024-10-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
