# Generated by Django 5.0.3 on 2024-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
