# Generated by Django 5.0.3 on 2024-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chapa_sub_method',
            field=models.CharField(blank=True, choices=[('telebirr', 'Telebirr'), ('cbe', 'CBE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'Paypal'), ('cash', 'Cash on Delivery')], default='chapa', max_length=100),
        ),
    ]
