# Generated by Django 5.0.3 on 2024-09-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='acount_status',
            new_name='account_status',
        ),
    ]
