# Generated by Django 5.0.3 on 2024-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/user_default_profile_image/img.png', null=True, upload_to='users/user_profile_images/'),
        ),
    ]
