# Generated by Django 5.0.3 on 2024-11-03 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment'),
        ('vendors', '0003_remove_vendor_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors.vendor'),
        ),
    ]
