# Generated by Django 5.0.3 on 2024-10-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_paid_order_address_order_payment_and_more'),
        ('payments', '0002_payment_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.payment'),
        ),
    ]
